services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: "soap-api"
    container_name: soap
    environment:
      POSTGRES_DB: soap_contact
      POSTGRES_USER: soap
      POSTGRES_PASSWORD: soap
    volumes:
      - soap_contact:/data/soap_contact
    ports:
      - "5433:5432"
    restart: unless-stopped
volumes:
  soap_contact:
    external: true