services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: "soap-api"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_DB}:/data/${POSTGRES_DB}
    ports:
      - "5433:5432"
    restart: unless-stopped
volumes:
  soap_contact:
    external: true